//
//  ProfilePresenter.swift
//  DailyApp
//
//  Created by Oleksandr Zavazhenko on 01/02/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfilePresentationLogic {
  
  func presentUserName(response: UserInfo.FetchUsername.Response)
  func presentConfigurationOfDarkModeSwitcher(response: UserInfo.CheckDarkMode.Response)
  func presentUserPick(response: UserInfo.FetchUserPick.Response)
  func presentUserStats(response: UserInfo.FetchStats.Response)
}

class ProfilePresenter: ProfilePresentationLogic {

  weak var viewController: ProfileDisplayLogic?
  
  // MARK: Do something


  func presentUserName(response: UserInfo.FetchUsername.Response) {

    let viewModel = UserInfo.FetchUsername.ViewModel(username: response.username)

    viewController?.displayUsername(viewModel: viewModel)

  }

  func presentConfigurationOfDarkModeSwitcher(response: UserInfo.CheckDarkMode.Response) {

    let viewModel = UserInfo.CheckDarkMode.ViewModel(isOn: response.isOn)

    viewController?.displayConfigurationOfDarkModeSwitcher(viewModel: viewModel)

  }

  func presentUserPick(response: UserInfo.FetchUserPick.Response) {

    let viewModel = UserInfo.FetchUserPick.ViewModel(image: (UIImage(contentsOfFile: response.imageName) ?? UIImage(named: "defaultUserPick")) ?? UIImage())

    viewController?.displayUserPick(viewModel: viewModel)

  }

  func presentUserStats(response: UserInfo.FetchStats.Response) {

    let stats = UserInfo.FetchStats.ViewModel.Stats(numberOfAllTasks: String(response.numberOfAllTasks),
                                                    numberOfCompletedTasks: String(response.numberOfCompletedTasks),
                                                    numberOfActiveTasks: String(response.numberOfActiveTasks),
                                                    percentage: response.percentage)

    let viewModel = UserInfo.FetchStats.ViewModel(stats: stats)

    viewController?.displayUserStats(viewModel: viewModel)
  }


}
