//
//  ListTasksModels.swift
//  DailyApp
//
//  Created by Oleksandr Zavazhenko on 30/01/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListTasks {
  
  enum FetchTasks {

    struct Request {

    }

    struct Response {
      var categories: [Category]
    }

    struct ViewModel {

      struct DisplayedCategories {
        var title: String
        var tasks: [Task]
      }

      var categories: [DisplayedCategories]
    }

  }

  enum CompleteTask {

    struct Request {
      var selectedTask: Task
    }

    struct Response {

    }

    struct ViewModel {

    }

  }

  enum GreetUser {

    struct Request {
      var timeNow: Date
    }

    struct Response {
      var periodOfDay: PeriodOfDaytime
    }

    struct ViewModel {
      var greetings: String
      var activityImage: String
    }

  }

  enum DeleteTask {

    struct Request {
      var selectedTask: Task
    }

    struct Response {

    }

    struct ViewModel {
      
    }

  }
}

enum PeriodOfDaytime {

  case morning, afternoon, evening, night

}
