//
//  CreateTaskModels.swift
//  DailyApp
//
//  Created by Oleksandr Zavazhenko on 30/01/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CreateTask {

  struct TaskFormFields {

    var title: String
    var category: Category
    var date: Date

  }

  struct CategoryFormFields {

    var title: String
    var label: String

  }

  enum DeleteCategory {

    struct Request {
      var categoryToDelete: Category
    }

    struct Response {

    }

    struct ViewModel {

    }

  }
  
  enum CreateTask {

    struct Request {
      var taskFormFields: TaskFormFields
    }

    struct Response {
      var task: Task
    }

    struct ViewModel {
      var task: Task
    }
  }

  enum CreateCategory {

    struct Request {
      var categoryFromFields: CategoryFormFields
    }

    struct Response {
      var category: Category
    }

    struct ViewModel {
      var category: Category
    }

  }

  enum FetchCategories {

    struct Request {

    }

    struct Response {
      var categories: [Category]
    }

    struct ViewModel {

      struct DisplayedCategories {

        var title: String
        var tasks: [Task]

      }
      var displayedCategories: [DisplayedCategories]
      var categories: [Category]
    }
  }
}
