//
//  CreateTaskPresenter.swift
//  DailyApp
//
//  Created by Oleksandr Zavazhenko on 30/01/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateTaskPresentationLogic {

  func presentCategories(response: CreateTask.FetchCategories.Response)

}

class CreateTaskPresenter: CreateTaskPresentationLogic {

  weak var viewController: CreateTaskDisplayLogic?
  
  // MARK: Do something

  func presentCategories(response: CreateTask.FetchCategories.Response) {


    var categories: [CreateTask.FetchCategories.ViewModel.DisplayedCategories] = []


    for category in response.categories {

      let tasks = category.tasks?.allObjects as? [Task]

      if let tasks = tasks,
         let title = category.title,
         let label = category.label {

        let newTitle = label + title
        let newCategory = CreateTask.FetchCategories.ViewModel.DisplayedCategories(title: newTitle, tasks: tasks)

        categories.append(newCategory)
      }
    }

    let viewModel = CreateTask.FetchCategories.ViewModel(displayedCategories: categories, categories: response.categories)

    viewController?.displayCategories(viewModel: viewModel)

  }
}
